name: Java CI with Maven & JaCoCo

on:
  push:
    branches: ["master", "feature/**"]
  pull_request:
    branches: ["master"]

jobs:

  featurebuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build & Test (Feature)
        run: mvn clean test

  masterbuild:
    needs: featurebuild
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build & Test (Master only)
        if: github.ref == 'refs/heads/master'
        run: mvn clean verify

      - name: Upload JaCoCo Report
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco
